### ISSUE TITLE
Weird welcome entry 

### ISSUE THREAD

**Issue by ghost** [pvanek/qlipper#13]
'Welcome to the Qlipper clipboard history applet'.
What is its sense?

**Comment by pvanek** [comment]
there has to be something when you open the context menu at first time I think. I'm pretty sure this stuff is a legacy of the original maintainer. Maybe the "about" and etc. menu entries would be sufficient.

**Comment by sunlight0258** [comment]
Can you provide a configuration item or checkbox so that users can set it not to display this paragraph on the pasteboard? Thank you very much.
