### ISSUE TITLE
Primary vs. clipboard content

### ISSUE THREAD

**Issue by palinek** [pvanek/qlipper#15]
I can't get working following scenario:
- select text `foo` with mouse (e.g. in some application that can not handle clibboard)
- select `foo` in qlipper (to put it into clipboard)
- paste `foo` from clipboard (into application which is aware of clipboard)

Am I missing something or qlipeer doesn't support primary/clipboard synchronization?

**Comment by pvanek** [comment]
primary clipboard is used if you enable Preferences/Use platform specific extensions. But it is not syncing between primary-clipboard.
Personally I don't use qlipper for primary.
But I'm open for suggestions...

**Comment by palinek** [comment]
> primary clipboard is used if you enable Preferences/Use platform specific extensions

I was  aware of that.

> But it is not syncing between primary-clipboard.But it is not syncing between primary-clipboard.

Would it be possible to implement such (optional) feature?
