### ISSUE TITLE
System QtSingleApplication not found

### ISSUE THREAD

**Issue by sxe** [pvanek/qlipper#2]
Hi, 

i cannot build version 2.0.2.

cmake -DCMAKE_INSTALL_PREFIX=/usr

gives me this error:

-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/lib/qt4/bin/qmake (found version "4.8.5") 
-- Use system Qxt Library: ON
-- Use system QtSA Library: ON
CMake Error at CMakeLists.txt:70 (message):
  System QtSingleApplication not found

Any idea whats going wrong?

Thank you

**Comment by pmattern** [comment]
As of 2015-12 this issue can be considered superseded by #25, can't it?

**Comment by palinek** [comment]
this is outdated now...
