### ISSUE TITLE
New release with Version 5?

### ISSUE THREAD

**Issue by agaida** [pvanek/qlipper#30]
set(QLIPPER_VERSION 5.0.0) is pushed long ago, but the latest release was in 2013

**Comment by Arnaudv6** [comment]
second that.
Distros can't update and stabilize if you provide no release :unamused:

**Comment by Arnaudv6** [comment]
This has to be reopened due to #38 being closed (other scope) before #30 actually is sorted.
Last release still dates back to 2013.

**Comment by palinek** [comment]
This one is not closed....

**Comment by Arnaudv6** [comment]
Right ! My bad, sorry.

**Comment by agaida** [comment]
fixed with pvanek/qlipper/pull/49

**Comment by Arnaudv6** [comment]
Thanks !
