### ISSUE TITLE
Tagging qlipper

### ISSUE THREAD

**Issue by agaida** [pvanek/qlipper#38]
Hi @pvanek - a new tag would be nice, we are on 5.0.0 and the last tag is 2.0.2 - looks strange and a little bit misleading, if one use git describe for package versions.

**Comment by goetzc** [comment]
Yes, a new release tarball please. 

As said by @Arnaudv6 (issue 30, same topic) usually distros don't update from git, they wait for a new release.

**Comment by agaida** [comment]
@pvanek - ping

**Comment by agaida** [comment]
@pvanek @luis-pereira @paulolieuthier @pmattern - i think we have a little communication problem here. We should try to solve that as I'm don't want to play the forking card (yet). But we have to improve the situation.

**Comment by pvanek** [comment]
actually what exactly do you need? All is in the git, and this is ongoing work. Do you want to publish some tarball somewhere?

**Comment by palinek** [comment]
Sorry, but I can't do much here -> I don't have any write permissions to the qlipper repo and I don't know Petr personaly...

**Comment by pvanek** [comment]
added palinek. Please note that I havent test qlipper with latest 2 patches so it can be broken completely

**Comment by palinek** [comment]
> added palinek. 

Fuh... that wash quick :)

> Please note that I havent test qlipper with latest 2 patches so it can be broken completely

@agaida are you providing the latest (git master) qlipper in some repository?

**Comment by agaida** [comment]
@pvanek - no problems anymore - but we should really make a release soon (and maybe talk more often). I started bringing LXQt and related packages to debian with the Debconf 2015 in Germany - and the situation was: last tag was 2.0xxx, CMake says 5.0 so i take the number in CMake for true. And if you look into the bugtracker it isn't only me, not a nice situation for distributions. 

@palinek - the latest git (yesterday) is in sid, i will today make a new build with the latest commits for lxqt-snapshots. If it works ok i will upload a new snapshot to sid.

**Comment by agaida** [comment]
^^ so one can see the 'problem' with the version: if tagged and release i can and will upload a proper qlipper 5.0.0-1

**Comment by palinek** [comment]
> ^^ so one can see the 'problem' with the version: if tagged and released i can and will upload a proper qlipper 5.0.0-1

How about some 4.9.9-rc~g<commit> ? And after the release/tag, the 5.0.0 will be uploaded...

**Comment by agaida** [comment]
maybe we should adopt the KDE numbering scheme for next versions - aka 4.9.96 or so  and avoid literals in the version no - the current uploaded version in debian is < 5.0.0-1 so there is no need to tag right now. It can be tagged if the release is ready - it would be nice to have this before debian freezes, a snapshot version in a stable release is not the very best idea if one can avoid it.

**Comment by agaida** [comment]
i think we can close this now
