### ISSUE TITLE
Kubuntu 13.10, KDE 4.10+

### ISSUE THREAD

**Issue by Shura0** [pvanek/qlipper#4]
qlipper works very strange on KDE 4.10 and above. I have enabled platform specific extensions, so it sohuld use mouse buffer and regular buffer, but it uses only buffer. It can fill mouse buffer or sometimes it fills regular buffer, but not both simultaneously.
Is it normal? Does make sense left or right click on qlipper tray icon?

**Comment by palinek** [comment]
Meanwhile the option to "synchronize primary/clipboard on selection" was added -> #21

@Shura0 can we close this now?
