### ISSUE TITLE
no sync between clipboard & PSE

### ISSUE THREAD

**Issue by Wonko7** [pvanek/qlipper#53]
Hi all,

I have "use platform specific extensions" & "synchronize clipboard & PSE" selected in my preferences.
When I select text, I can mouse paste it, but ctrl+v pastes something else. So I'm guessing sync isn't working?

I'm using: 
- qlipper's 5.0.0 release, https://github.com/pvanek/qlipper/archive/5.0.0.tar.gz
- lxqt 0.11 with xmonad
- linux/gentoo

I'm not seeing anything in .xsession-errors. 

Anything else you might need that could help?

**Comment by palinek** [comment]
Primary selection & clipboard aren't synchronized automagicaly, but olny on item selection... And therefore the option is called "Synchronize clipboard \& PSE when item selected"

**Comment by Wonko7** [comment]
So selecting means that I have to click on the systray icon, and then click on the item I wanted to paste, and then I can ctrl+v it?
Because really, I wanted to use ctrl+v rather than use the mouse in the first place.

Could an automagical sync be considered as an enhancement? I fail to see the usefulness of the current option (if I understand it correctly), but I'd welcome an additional automagical preference.

**Comment by agaida** [comment]
@Wonko7 - it is useful, especially if one works with a large set of possible things to paste - i have sometimes 70-100 items in the list - and i love this feature - i was wrong to assume that this feature will jump in at the moment when i mark something

And yes - such a thing would be also nice to have.

**Comment by Wonko7** [comment]
Right, in my context I wasn't seeing it. 
Btw, the full option name being "Synchronize clipboard & PSE when item selected", I thought that meant when the text was selected, maybe something like "when menu item is selected" or "when item is clicked" would avoid confusion on the matter.

**Comment by palinek** [comment]
> So selecting means that I have to click on the systray icon, and then click on the item I wanted to paste, and then I can ctrl+v it?

That's one way. But you can use a keyboard shortcut to raise the menu and select the item by keyboard only.

> I fail to see the usefulness of the current option (if I understand it correctly),

That's for those users wanting to have full control of what is in primary and what in clipboard. I personaly don't like to have everything what is selected to be synchronized into clipboard.

> but I'd welcome an additional automagical preference.

For sure it can be done.

**Comment by palinek** [comment]
Have a look on #54

**Comment by Wonko7** [comment]
Awesome, thanks! It's not building right now, but I'll track the instant_sync branch for changes.

```
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.cpp: In member function ‘void QlipperModel::indexTriggered(const QModelIndex&)’:
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.cpp:228:30: warning: extended initializer lists onlyavailable with -std=c++11 or -std=gnu++11
     list.at(row).toClipboard({QlipperItem::ToCurrent
                              ^
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.cpp:231:23: warning: extended initializer lists onlyavailable with -std=c++11 or -std=gnu++11
                     )});
                       ^
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.cpp:231:23: error: no matching function for call to ‘QlipperItem::toClipboard(<brace-enclosed initializer list>) const’
In file included from /var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.h:27:0,
                 from /var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlippermodel.cpp:25:
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlipperitem.h:62:10: note: candidate: void QlipperItem::toClipboard(const Actions&) const
     void toClipboard(const Actions & actions) const;
          ^
/var/tmp/portage/x11-misc/qlipper-9999/work/qlipper-9999/src/qlipperitem.h:62:10: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const Actions& {aka const QFlags<QlipperIte
m::Action>&}’
make[2]: *** [CMakeFiles/qlipper.dir/build.make:266: CMakeFiles/qlipper.dir/src/qlippermodel.cpp.o] Error 1
```

**Comment by palinek** [comment]
@Wonko7 pushed fixup..

**Comment by Wonko7** [comment]
Yup, that did it, thanks a lot :)

**Comment by aramazano** [comment]
> Btw, the full option name being "Synchronize clipboard & PSE when item selected", I thought that meant when the text was selected, maybe something like "when menu item is selected" or "when item is clicked" would avoid confusion on the matter.

I second this. Before seeing this discussion, I for one, was assuming that "Synchronize clipboard & PSE when item selected" meant "Synchronize clipboard & PSE when something on the screen is mouse-selected". Of course, I couldn't then make sense of what the other option ("do it instantly") really meant.

Current wording for this setting is ambiguous and misleading. Changing it to something as @Wonko7 suggested would be very nice.
