### ISSUE TITLE
Require c++11

### ISSUE THREAD

**Issue by palinek** [pvanek/qlipper#55]
I would be happy if we can use c++11 features in qlipper's code.

Can I update build system to require c++11 compiler? Or are there any objections?

**Comment by agaida** [comment]
https://en.wikipedia.org/wiki/C%2B%2B11 - i think no - it should have reached the most distributions after 5 years in the wild

**Comment by pvanek** [comment]
my only question - is it available in Qt5 mingw version for Windows? Does RHEL6/Centos6 support this?

**Comment by palinek** [comment]
> mingw version for Windows

Why? Isn't the visual studio available for free already (e.g. https://www.visualstudio.com/vs/community/)?

> Does RHEL6/Centos6 support this?

I don't get this requiremet either:
1. RHEL is for server and qlipper is a desktop app.
2. RHEL6 doesn't know even about Qt5 anything. (I don't know much about backports etc...)

**Comment by martinrotter** [comment]
I believe MinGW supports C++ 11 just fine. They distribute rather newer versions of MinGW with Qt bundle for some years, I have used C++ 11 with MinGW in the past without problem.
