### ISSUE TITLE
Remove clipboard items from context menu

### ISSUE THREAD

**Issue by palinek** [pvanek/qlipper#61]
I would like to remove the clipboard items from context menu. So the items will be only in menu showed upon the (left)clik on tray icon or upon the shortcut. In context menu ((right)click on tray icon) will just be the static items (clear, configure, about, quit).

Any objections?

**Comment by pmattern** [comment]
Absolutely agree. If I'm not mistaken this would make Qlipper behave like all kinds of other panel objects do, namely actual functionality is covered by left click, configuration by the context menu.
