### ISSUE TITLE
Missing translations in systray menu (qlipper 5.1.1)

### ISSUE THREAD

**Issue by rbuj** [pvanek/qlipper#78]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Bionic Beaver (development branch)
Release:	18.04
Codename:	bionic

$ dpkg -s qlipper | grep '^Version:'
Version: 1:5.1.1-2

$ echo $LANG
ca_ES.UTF-8

![captura de pantalla 2017-12-09 a les 17 08 30](https://user-images.githubusercontent.com/10171411/33797226-7fd5b7c8-dd04-11e7-8593-aca652d467af.png)

**Comment by agaida** [comment]
if you need a translation the best way to get one is to provide one .. PRs welcome

**Comment by rbuj** [comment]
Thanks, but Catalan translation is 100% complete using the current ts file, only systray menu is displayed in English, because of an outdated ts. QlipperMenuView was deleted in https://github.com/pvanek/qlipper/commit/4daa79091dc5f0331e5f5b0d184b035b9f42e84f

**Comment by agaida** [comment]
i guess you are better in using Qt Linguist - could you update the ts file(s) please.

**Comment by palinek** [comment]
fixed in #77
