### ISSUE TITLE
Fix language/country codes (sr_RS)

### ISSUE THREAD

**Issue by scootergrisen** [pvanek/qlipper#91]
It seems qlipper_it.ts is using:

    <TS version="2.1" language="sr_RS">

And qlipper_sr.ts is using:

    <TS version="2.1" language="sr_RS">

Maybe change to:

    <TS version="2.1" language="it">
    <TS version="2.1" language="sr">

**Comment by palinek** [comment]
Would you mind create a PR for this?

**Comment by scootergrisen** [comment]
https://github.com/pvanek/qlipper/pull/92
https://github.com/pvanek/qlipper/pull/93
